### ISSUE TITLE
Symbol’s function definition is void: hide-mode-line-mode.

### ISSUE THREAD

**Issue by Ypot** [positron-solutions/moc#1]
Hi

When M-x mc-present-mode
I receive this error:
cond: Symbol’s function definition is void: hide-mode-line-mode.

Maybe because I have already hidden?

Offtopic: A non-developer should use this package or macro slides, or both?

**Comment by psionic-k** [comment]
`mc-present-mode` was deprecated in favor of `mc-dispatch`, a control board for various settings.

You can downgrade or we can figure out how to get what you need into `mc-dispatch` although that will definitely take longer and require some deliberate feedback.  Let me know which direction you want to take.

Check news for the new features.  I'll be doing a demo video today.

In general, pre-1.0 packages have no stability contract.  There's simply too much that is uncertain about what will be valuable or how the architecture should look.

dslide (macro slides is an old name) has matured quite a bit and is maybe 90% of the way to 1.0.  I recommend it for use as the markup on the user side will only get simpler moving forward.

**Comment by psionic-k** [comment]
This was cleaned up while prepping for package archives
